apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: ibm-entitlement-key
  namespace: openshift-marketplace
spec:
  encryptedData:
    .dockerconfigjson: AgCMuCr/DA2TVtZrtHBQZ0HQARTGFZiIjB4VyHiuDRjVKnloR3dTRynEbz2IozNMCo7c8oB2mHjkL9om8o++LUAVh8wdRGFm5LVSowJTldbvEQLDTcZqtMhHT7K6ZRYMFCgqXhfFBKtDpQLddBdK6YgfG8NpweDddAOj6oGa2dhJHDAAkClpBUI9Cpi5DkoF8TPARnKdzl6TNjypoUGMXyHF/yB/Rw41AtVJcf/1HzoBOrJe92wrJRHqFxZn2l+NdBwH5YZ6GTirfOlJ72RFCC55zEzX7GfKoHF0g+yL66xyx/H9gYkOiGTlRDIh/F9VzLlnGj/W0y/9lQMgKOnVLmllXIJpZU+cVhYBUIcb1XoX6fkTrQnWqIyYMqS2pgUWBlrg58UAK4gfiVqp1diMvUqRgjZ3okSwl9EAMZwRmZupHf3x9sPd0WNnvyID3X6zOnXZQxRpptjUErh7oGKsgRWMhYRb7RnE/XfPtc2aGw/thxvDObAEHx41Kmy45MO3AH8es1YPnUBfWcx6ATozM1YtvqcN2czbLpzRuRMdO2kChC2ID1khGhRDkXbpLJ/6PvdhaYE6YkZ9em8goMNPZSXjJIdqwYJht0ASyc9XIKQlnOCaGsCA8buI6i0xV9pmhgAHwspwf/MkwGbkDxacoDiAoxvWow90YG7gsgdArm1hvcQkprkafRMsEP+5nSZA911p3bs/WekXGsoxqcSbKDIZqueIZpikZRnQGnXgxWDGY4aPUvJw8hQrRMxHNKEEJ7/k05RcesenNtHDpTX9abaZ0Ix3e6eCzNHhc8gaBw9Vcrq/D1IErwL3cG5eBUX6v6aFBo9lX5bRX5Xy/3vLZciCSjuEgeAtyhnPI1G8Rk5Mz9QtGknaysG7sdbxDj1ySJJtCvmMjKqhspYILeE8yS1dVu7AW9Fe3MwOLRKEcF1busvE14nO23kNH31snFK3E9TNRkJCUl7y6d227TtNApWRNXQpbuJw+FPDQPzk0JO9KBHluvYdclLwfZCEVXGiDcWW4C8kNgmeTK4a5wEPRgpop/j2obyrzEti4s3FYB7hJCQHe9TubRPvhFRG27EAq8Ct6//Ysw/q/Mm8SllIcDQ3Zt5RUUOgjRTtvOTqHMmiwvufcq/Xr4fb7gKdfyKcIm1+cFEowHftHmnV4VZyzdS7pG/EcPDAB9jpg+E9PLY7Ocw9RLwGTYsSdGYBq2PW9kuu8QDOPpi7aiakOIB7GWjvYfbE2m5QUu9zT2Y4iy1s87H2S9BgzP3W+v28KyWI8qsPHXjO3Ju71A4Ur0QA701HIOYK+uHt/0CqdfqUzVTTLlwHWkYtX/06pNKZn+SDgAu+
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: ibm-entitlement-key
      namespace: openshift-marketplace
    type: kubernetes.io/dockerconfigjson

