apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: namespace-gitops-cp-waiops-eventmgr
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: 1-infrastructure
  source:
    path: payload/1-infrastructure/namespace/gitops-cp-waiops-eventmgr/namespace
    repoURL: >-
      https://github.com/cloud-native-toolkit-test/gitops-cp-waiops-eventmgr-ocp4
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  ignoreDifferences: []
